### PR TITLE
Small typos

### PR DESCRIPTION
**Pull request by TrymDev**
#155

### CODE REVIEW

**Review by kazuk — APPROVED** [review]
Thank you @TrymDev .

**Review by kazuk — CHANGES_REQUESTED** [review]
please add CHANGELOG like a bellow.

```
### Fixed

- Fix some typos ([#157](https://github.com/SpringQL/SpringQL/pull/157))
```

**Review by laysakura — APPROVED** [review]
@TrymDev We appreciate your contribution.

Recently, we have changed CHANGELOG.md policy a bit.

https://github.com/SpringQL/SpringQL/blob/main/CHANGELOG.md
> We originally added ### For developers sections in order to separate changes for end-users and developers. All other sections are for end-users.

You may feel free to add `For developers` section if you want.

Anyway, I approve this PR. I will merge this after your response or further commit on CHANGELOG.md.

**Comment by laysakura** [comment]
No reply for 8 days. I merge this PR without CHANGELOG update.

**Pull request merged**
